### ISSUE TITLE
Size of jQuery with no modules

### ISSUE THREAD

**Issue by adrianmiu** [jgallen23/jquery-builder#10]
jQuery 2.0 without any modules is 112.57 Kb. This can't be right, can it?

**Comment by jgallen23** [comment]
That is un-minified.  Make sure you click the minified checkbox.  Filesize: 40.29 Kb / Gzip: 13.93 Kb

**Comment by adrianmiu** [comment]
I've seen the minified checkbox. I was referring to the fact that ZERO modules should translate to ZERO kb. 
If I don't want ajax and animations I don't want Deferred (assuming Deferred is only used by ajax and animations), yet Deferred is there.

Obviously nobody needs jQuery with no modules but maybe this is a sign that your dependency detection is not working properly.

**Comment by jgallen23** [comment]
jQuery only exposes certain "modules" that can be removed.  The rest is jQuery core.

**Comment by adrianmiu** [comment]
I see. Sorry for the intrusion.
