### ISSUE TITLE
Add “latest” version

### ISSUE THREAD

**Issue by doktorbro** [jgallen23/jquery-builder#12]
I write a [jQuery plugin](https://github.com/penibelst/imadaem), that only needs two modules: `css` and `dimensions`. In the plugin’s description I would like to point the users at the latest version of your custom version. By “latest” I mean the official definition implicated in the URL [jquery-latest.min.js](http://code.jquery.com/jquery-latest.min.js) of the jQuery Foundation hosted version.

What do you think about adding the `dist/latest` directory? Developers like me could always use the unchanged custom link, e. g.

``` shell
https://raw.github.com/jgallen23/jquery-builder/master/dist/latest/jquery-deprecated.js
```

That way would simplify things a bit.

**Comment by jgallen23** [comment]
that's a good idea.  I'll look into it.
