### ISSUE TITLE
raw.github.com doesn't spit out JS file, just HTML

### ISSUE THREAD

**Issue by jtenner** [jgallen23/jquery-builder#13]
```
C:\Users\jtenner\Desktop\Node-Webkit\CappricioJS>jquery-builder --exclude css,de
precated,dimensions,effects,event,alias,offset,wrap -m > jquery.ajax.min.js
```

It spits out an HTML file.

It's targeting the <code>raw.github.com</code> url and spits out an HTML page instead of a file.

I can make a pull request to target rawgithub.com and it should work.

**Comment by jgallen23** [comment]
a pull request would be great!  Thanks

**Comment by jtenner** [comment]
Fast response!  Will do!

**Comment by jtenner** [comment]
https://github.com/jgallen23/jquery-builder/pull/14

**Comment by jtenner** [comment]
This still isn't working. It worked on my PC before hand, and now it spits out a 404 message.

Dangit.

**Comment by jgallen23** [comment]
you need event-alias instead of event,alias

**Comment by jtenner** [comment]
Oh okay. That looks like the problem. Is the code actually working then?
