### ISSUE TITLE
Add jQuery 1.11.0

### ISSUE THREAD

**Issue by coliff** [jgallen23/jquery-builder#15]
Would be good to add the latest version of jQuery v1.11.0.

**Comment by andismith** [comment]
+1

**Comment by mm-tom** [comment]
+1 
Is this repo dead now though? Seems like it :/

**Comment by jgallen23** [comment]
Not dead. Just no free time. Will welcome pull requests

**Comment by mm-tom** [comment]
Ok, well I know that feeling. If this was within my field of expertise I'd gladly contribute, but alas not. NP.

**Comment by peterkinmond** [comment]
Added a pull request for this #18

**Comment by jgallen23** [comment]
thanks, this is live now
